server:
  port: 8080
  session-timeout: 1200

spring:
  main:  
    show-banner: true

  jade4j:
    caching: false
    

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: sampleapp
      client-secret: wlpaBFBJTzmRLcLInQcIiS8ggLclLjQg
      access-token-uri: http://localhost:9999/api/oauth2/token
      user-authorization-uri: http://localhost:9999/api/oauth2/authorize
      scope: admin,user
      authorized-grant-types: authorization_code,refresh_token,client_credentials
      
    resource:
      user-info-uri: http://localhost:9999/api/profile
      prefer-token-info: false
      
    custom:
      # for single sign out(global logout)
      server-logout-url: http://localhost:9999/logout
      
      # redirect url for after single signed out
      server-logouted-redirect-url: http://localhost:8080/

logging:
  # log configuration detail -> src/main/resources/logback.xml
  level:
    ROOT: INFO
    
    # for framework log
    org.springframework: WARN
    org.springframework.jdbc: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # for application log
    springboot.oauth.sample: INFO
    springboot.oauth.sample.core.config.AccessLoggingFilterConfig: INFO  # start/end log

      